services:

  # Kafka
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.20.128:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ~/microservices/kafka/data:/var/lib/kafka/data
    networks:
      - microservices-net
    restart: unless-stopped

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: microservices
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/microservices/mysql/data:/var/lib/mysql
      - ~/microservices/mysql/conf:/etc/mysql/conf.d
      - ~/microservices/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - microservices-net
    restart: unless-stopped

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass 123456
    volumes:
      - ~/microservices/redis/data:/data
      - ~/microservices/redis/conf:/usr/local/etc/redis
    networks:
      - microservices-net
    restart: unless-stopped

  # Elasticsearch
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - ~/microservices/elasticsearch/data:/usr/share/elasticsearch/data
      - ~/microservices/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    networks:
      - microservices-net
    restart: unless-stopped

  # kibana
  kibana:
    image: kibana:7.12.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - microservices-net
    depends_on:
      - elasticsearch
    restart: unless-stopped



  # Nacos
  nacos:
    image: nacos/nacos-server:v3.0.0
    container_name: nacos
    hostname: nacos
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - NACOS_AUTH_TOKEN=XuK7K5GgX9FP0SqLcX8F/o5EEwsXlyV2dFp90iFs0Kg=
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos

    volumes:
      - ~/microservices/nacos/logs:/home/nacos/logs
      - ~/microservices/nacos/logs:/home/nacos/logs
    depends_on:
      - mysql
    networks:
      - microservices-net
    restart: unless-stopped

  # Canal
  canal:
    image: canal/canal-server:v1.1.7
    container_name: canal
    hostname: canal
    depends_on:
      - mysql
    environment:
      canal.instance.master.address: mysql:3306
      canal.instance.dbUsername: canal
      canal.instance.dbPassword: canal123
      canal.instance.connectionCharset: UTF-8
      canal.instance.tsdb.enable: "true"
      canal.instance.gtidon: "false"
      canal.instance.filter.regex: ".*\\..*"
      canal.instance.spring.startup.auto: "true"
    volumes:
      - ~/microservices/canal/conf:/home/canal/conf
    ports:
      - "11111:11111"
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge
    name: microservices-network